spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  #페이지 1부터 처리하기 위함 ex) page=1 size=5  -> 0,1,2,3,4
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5 #페이지 사이즈 Default지정

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:h2:mem:hodolog
    username: sa
    password:
    driver-class-name: org.h2.Driver